// Generated by research/data/cards/build_cards.py from research/data/cards/curated-cards.json
// (issuer pages, checked 2026-09-11), the CFPB TCCP survey, and game/public/cards/art/manifest.json.
// Do not edit by hand; rerun the script.

import type { CuratedCard } from "../sim/money/types.ts";

export const CURATED_AS_OF = "Sep 11, 2026";
export const TCCP_AS_OF = "Dec 31, 2025";

/** 23 real cards for the Card Shop. */
export const CURATED: CuratedCard[] = [
  {
    "slug": "chase-sapphire-preferred",
    "name": "Chase Sapphire Preferred",
    "issuer": "Chase",
    "network": "Visa",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 95,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Chase Ultimate Rewards",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "x",
        "note": "Chase Travel"
      },
      {
        "category": "dining",
        "rate": 3,
        "unit": "x"
      },
      {
        "category": "gas",
        "rate": 3,
        "unit": "x",
        "note": "gas stations and EV charging (new 2026)"
      },
      {
        "category": "streaming",
        "rate": 3,
        "unit": "x",
        "note": "select streaming services"
      },
      {
        "category": "groceries",
        "rate": 3,
        "unit": "x",
        "note": "online grocery only, excl. Target/Walmart/wholesale clubs"
      },
      {
        "category": "travel",
        "rate": 2,
        "unit": "x",
        "note": "other travel"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "x"
      }
    ],
    "welcomeOffer": {
      "text": "Earn 75,000 bonus points after you spend $5,000 on purchases in the first 3 months",
      "valueUsd": 750.0,
      "spend": 5000,
      "months": 3
    },
    "introApr": null,
    "regularApr": "19.24%-27.49% Variable",
    "foreignFee": "None",
    "perks": [
      "$100 annual Chase Travel hotel credit",
      "Up to $120 Global Entry/TSA PreCheck/NEXUS credit every 4 years",
      "Complimentary DashPass plus $10/month DoorDash promo",
      "Purchase protection (120 days, $500/item)",
      "Points worth up to 1.5x via Points Boost on Chase Travel"
    ],
    "sourceUrl": "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/chase-sapphire-preferred.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire-preferredcard2026.png"
    },
    "terms": {
      "id": "jpmorgan-chase-bank-sapphire-preferred",
      "institution": "Jpmorgan Chase Bank, National Association",
      "issuerKey": "CHASE",
      "productName": "Sapphire Preferred",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": 0.2749,
      "aprPoor": 0.2749,
      "aprGood": 0.2749,
      "aprGreat": 0.2649,
      "aprMin": 0.1924,
      "aprMax": 0.2749,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": 0.05,
      "btFeeMin": 5.0,
      "cashApr": 0.2849,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 21.0,
      "annualFee": 95.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards",
        "Travel-related rewards"
      ]
    },
    "tccpId": "jpmorgan-chase-bank-sapphire-preferred"
  },
  {
    "slug": "chase-sapphire-reserve",
    "name": "Chase Sapphire Reserve",
    "issuer": "Chase",
    "network": "Visa",
    "creditNeeded": "excellent",
    "secured": false,
    "student": false,
    "annualFee": 795,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Chase Ultimate Rewards",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 8,
        "unit": "x",
        "note": "Chase Travel"
      },
      {
        "category": "travel",
        "rate": 4,
        "unit": "x",
        "note": "flights and hotels booked direct"
      },
      {
        "category": "dining",
        "rate": 3,
        "unit": "x"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "x"
      }
    ],
    "welcomeOffer": {
      "text": "Earn 100,000 bonus points after you spend $6,000 on purchases in the first 3 months",
      "valueUsd": 1000.0,
      "spend": 6000,
      "months": 3
    },
    "introApr": null,
    "regularApr": "19.49%-27.99% Variable",
    "foreignFee": "None",
    "perks": [
      "$300 annual travel credit",
      "Priority Pass + Chase Sapphire Lounges (1,300+ lounges)",
      "$500/yr The Edit hotel credit",
      "$300 dining credit and $300 StubHub credit",
      "Points worth up to 2x via Points Boost"
    ],
    "sourceUrl": "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/chase-sapphire-reserve.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_reserve_card_Halo.png"
    },
    "terms": {
      "id": "jpmorgan-chase-bank-sapphire-reserve",
      "institution": "Jpmorgan Chase Bank, National Association",
      "issuerKey": "CHASE",
      "productName": "Sapphire Reserve",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": 0.2799,
      "aprPoor": 0.2799,
      "aprGood": 0.2799,
      "aprGreat": 0.2799,
      "aprMin": 0.1949,
      "aprMax": 0.2799,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": 0.05,
      "btFeeMin": 5.0,
      "cashApr": 0.2849,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 21.0,
      "annualFee": 795.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards",
        "Travel-related rewards"
      ]
    },
    "tccpId": "jpmorgan-chase-bank-sapphire-reserve"
  },
  {
    "slug": "chase-freedom-unlimited",
    "name": "Chase Freedom Unlimited",
    "issuer": "Chase",
    "network": "Visa",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "percent",
        "note": "Chase Travel"
      },
      {
        "category": "dining",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "drugstores",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "everything",
        "rate": 1.5,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a $200 bonus after you spend $500 on purchases in the first 3 months",
      "valueUsd": 200.0,
      "spend": 500,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 15 months",
      "balanceTransfers": "0% for 15 months",
      "btFee": "balance transfer fee applies (see pricing and terms)"
    },
    "regularApr": "18.24%-27.74% Variable",
    "foreignFee": "3%",
    "perks": [
      "Unlimited 1.5% on everything",
      "6 months complimentary DashPass",
      "Purchase protection (120 days, $500/item)",
      "Rewards tracked as Ultimate Rewards points (1 cent each)"
    ],
    "sourceUrl": "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/chase-freedom-unlimited.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://www.chase.com/content/dam/unified-assets/card-art/chase-freedom/freedom-unlimited/card_freedomUtld_V.png"
    },
    "terms": {
      "id": "jpmorgan-chase-bank-freedom-unlimited",
      "institution": "Jpmorgan Chase Bank, National Association",
      "issuerKey": "CHASE",
      "productName": "Freedom Unlimited",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": 0.2774,
      "aprPoor": 0.2774,
      "aprGood": 0.2774,
      "aprGreat": 0.2674,
      "aprMin": 0.1824,
      "aprMax": 0.2774,
      "introApr": 0.0,
      "introMonths": 15.0,
      "btApr": 0.0,
      "btMonths": 15.0,
      "btFeePct": 0.05,
      "btFeeMin": 5.0,
      "cashApr": 0.2849,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 21.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards",
        "Travel-related rewards"
      ]
    },
    "tccpId": "jpmorgan-chase-bank-freedom-unlimited",
    "unverified": true,
    "unverifiedFields": [
      "introApr.btFee"
    ]
  },
  {
    "slug": "chase-freedom-flex",
    "name": "Chase Freedom Flex",
    "issuer": "Chase",
    "network": "Mastercard",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "rotating",
        "rate": 5,
        "unit": "percent",
        "cap": "$1,500 combined per quarter, activation required",
        "annualCap": 6000.0,
        "note": "quarterly categories e.g. gas, grocery, select merchants"
      },
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "percent",
        "note": "Chase Travel"
      },
      {
        "category": "dining",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "drugstores",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a $200 bonus after you spend $500 on purchases in the first 3 months",
      "valueUsd": 200.0,
      "spend": 500,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 15 months",
      "balanceTransfers": "0% for 15 months",
      "btFee": "balance transfer fee applies (see pricing and terms)"
    },
    "regularApr": "18.24%-27.74% Variable",
    "foreignFee": "3% (Chase eliminating it on Sept 20, 2026)",
    "perks": [
      "5% quarterly rotating categories",
      "6 months complimentary DashPass",
      "Purchase protection (120 days, $500/item)",
      "Cell phone protection (World Elite Mastercard)"
    ],
    "sourceUrl": "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/chase-freedom-flex.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://www.chase.com/content/dam/unified-assets/card-art/chase-freedom/freedom-flex/card_freedomFlex_MC.png"
    },
    "terms": {
      "id": "jpmorgan-chase-bank-freedom-flex",
      "institution": "Jpmorgan Chase Bank, National Association",
      "issuerKey": "CHASE",
      "productName": "Freedom Flex",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": 0.2774,
      "aprPoor": 0.2774,
      "aprGood": 0.2774,
      "aprGreat": 0.2474,
      "aprMin": 0.1824,
      "aprMax": 0.2774,
      "introApr": 0.0,
      "introMonths": 15.0,
      "btApr": 0.0,
      "btMonths": 15.0,
      "btFeePct": 0.05,
      "btFeeMin": 5.0,
      "cashApr": 0.2849,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 21.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards",
        "Travel-related rewards"
      ]
    },
    "tccpId": "jpmorgan-chase-bank-freedom-flex",
    "unverified": true,
    "unverifiedFields": [
      "introApr.btFee",
      "topPerks: cell phone protection"
    ]
  },
  {
    "slug": "amex-platinum",
    "name": "The Platinum Card from American Express",
    "issuer": "American Express",
    "network": "Amex",
    "creditNeeded": "excellent",
    "secured": false,
    "student": false,
    "annualFee": 895,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Amex Membership Rewards",
    "centsPerPoint": 0.6,
    "earn": [
      {
        "category": "travel",
        "rate": 5,
        "unit": "x",
        "cap": "$500,000 per calendar year",
        "annualCap": 500000.0,
        "note": "flights booked direct with airlines or via Amex Travel"
      },
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "x",
        "note": "prepaid hotels on Amex Travel"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "x"
      }
    ],
    "welcomeOffer": {
      "text": "Earn 100,000 points after you spend $6,000 in the first 6 months (offers vary by applicant)",
      "valueUsd": 600.0,
      "spend": 6000,
      "months": 6
    },
    "introApr": null,
    "regularApr": "19.49%-28.49% Variable (Pay Over Time)",
    "foreignFee": "None",
    "perks": [
      "Global Lounge Collection: 1,550+ lounges incl. Centurion",
      "$600 hotel credit (FHR/Hotel Collection)",
      "$400 Resy credit and $300 digital entertainment credit",
      "$200 Uber Cash + $200 airline fee credit",
      "Cell phone protection (up to $800/claim)"
    ],
    "sourceUrl": "https://www.americanexpress.com/us/credit-cards/card/platinum/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/amex-platinum.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://icm.aexp-static.com/acquisition/card-art/NUS000000237_480x304_straight_withname.png"
    },
    "terms": {
      "id": "american-express-national-bank-the-platinum-card",
      "institution": "American Express National Bank",
      "issuerKey": "AMERICAN_EXPRESS",
      "productName": "The Platinum Card®",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": 0.2899,
      "aprPoor": null,
      "aprGood": 0.2899,
      "aprGreat": 0.2524,
      "aprMin": 0.1949,
      "aprMax": 0.2849,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 25.0,
      "annualFee": 895.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Other rewards"
      ]
    },
    "tccpId": "american-express-national-bank-the-platinum-card",
    "unverified": true,
    "unverifiedFields": [
      "welcomeOffer"
    ]
  },
  {
    "slug": "amex-gold",
    "name": "American Express Gold Card",
    "issuer": "American Express",
    "network": "Amex",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 325,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Amex Membership Rewards",
    "centsPerPoint": 0.6,
    "earn": [
      {
        "category": "dining",
        "rate": 4,
        "unit": "x",
        "cap": "$50,000/yr then 1x",
        "annualCap": 50000.0,
        "note": "restaurants worldwide"
      },
      {
        "category": "groceries",
        "rate": 4,
        "unit": "x",
        "cap": "$25,000/yr then 1x",
        "annualCap": 25000.0,
        "note": "U.S. supermarkets"
      },
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "x",
        "note": "prepaid hotels via Amex Travel"
      },
      {
        "category": "travel",
        "rate": 3,
        "unit": "x",
        "note": "flights direct or via Amex Travel"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "x"
      }
    ],
    "welcomeOffer": {
      "text": "Earn up to 100,000 points after you spend $8,000 in the first 6 months (offers vary by applicant)",
      "valueUsd": 600.0,
      "spend": 8000,
      "months": 6
    },
    "introApr": null,
    "regularApr": "19.49%-28.49% Variable (Pay Over Time)",
    "foreignFee": "None",
    "perks": [
      "$120 Uber Cash ($10/month)",
      "$120 dining credit ($10/month)",
      "$100 Resy credit",
      "$84 Dunkin' credit",
      "Purchase protection"
    ],
    "sourceUrl": "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/amex-gold.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://icm.aexp-static.com/acquisition/card-art/NUS000000174_480x304_straight_withname.png"
    },
    "terms": {
      "id": "american-express-national-bank-american-express-gold-card",
      "institution": "American Express National Bank",
      "issuerKey": "AMERICAN_EXPRESS",
      "productName": "American Express® Gold Card",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": 0.2899,
      "aprPoor": null,
      "aprGood": 0.2899,
      "aprGreat": 0.2724,
      "aprMin": 0.1949,
      "aprMax": 0.2849,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 25.0,
      "annualFee": 325.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Other rewards"
      ]
    },
    "tccpId": "american-express-national-bank-american-express-gold-card",
    "unverified": true,
    "unverifiedFields": [
      "welcomeOffer"
    ]
  },
  {
    "slug": "amex-blue-cash-everyday",
    "name": "Blue Cash Everyday Card from American Express",
    "issuer": "American Express",
    "network": "Amex",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "groceries",
        "rate": 3,
        "unit": "percent",
        "cap": "$6,000/yr then 1%",
        "annualCap": 6000.0,
        "note": "U.S. supermarkets"
      },
      {
        "category": "gas",
        "rate": 3,
        "unit": "percent",
        "cap": "$6,000/yr then 1%",
        "annualCap": 6000.0,
        "note": "U.S. gas stations"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent",
        "note": "also 3% on U.S. online retail, $6,000/yr cap"
      }
    ],
    "welcomeOffer": {
      "text": "Earn $200 back after you spend $1,000 in the first 3 months (offers vary by applicant)",
      "valueUsd": 200.0,
      "spend": 1000,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 15 months",
      "balanceTransfers": "0% for 15 months (request within 60 days)"
    },
    "regularApr": "19.49%-28.49% Variable",
    "foreignFee": "2.7%",
    "perks": [
      "$84/yr Disney streaming credit",
      "3% at U.S. supermarkets, gas and online retail",
      "Purchase protection (90 days)",
      "Cash back redeemable as statement credit"
    ],
    "sourceUrl": "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/amex-blue-cash-everyday.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://icm.aexp-static.com/acquisition/card-art/NUS000000305_480x304_straight_withname.png"
    },
    "terms": {
      "id": "american-express-national-bank-blue-cash-everyday-card",
      "institution": "American Express National Bank",
      "issuerKey": "AMERICAN_EXPRESS",
      "productName": "Blue Cash Everyday® Card",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": 0.2899,
      "aprPoor": null,
      "aprGood": 0.2899,
      "aprGreat": 0.2699,
      "aprMin": 0.1949,
      "aprMax": 0.2849,
      "introApr": 0.0,
      "introMonths": 15.0,
      "btApr": 0.0,
      "btMonths": 15.0,
      "btFeePct": 0.03,
      "btFeeMin": 5.0,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.027,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards"
      ]
    },
    "tccpId": "american-express-national-bank-blue-cash-everyday-card",
    "unverified": true,
    "unverifiedFields": [
      "welcomeOffer",
      "introApr",
      "regularApr"
    ]
  },
  {
    "slug": "amex-blue-cash-preferred",
    "name": "Blue Cash Preferred Card from American Express",
    "issuer": "American Express",
    "network": "Amex",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 95,
    "firstYearFeeWaived": true,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "groceries",
        "rate": 6,
        "unit": "percent",
        "cap": "$6,000/yr then 1%",
        "annualCap": 6000.0,
        "note": "U.S. supermarkets"
      },
      {
        "category": "streaming",
        "rate": 6,
        "unit": "percent",
        "note": "select U.S. streaming subscriptions"
      },
      {
        "category": "gas",
        "rate": 3,
        "unit": "percent",
        "note": "U.S. gas stations"
      },
      {
        "category": "transit",
        "rate": 3,
        "unit": "percent",
        "note": "taxis, rideshare, parking, tolls, trains, buses"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a $300 statement credit after you spend $3,000 in the first 6 months (offers vary by applicant)",
      "valueUsd": 300.0,
      "spend": 3000,
      "months": 6
    },
    "introApr": {
      "purchases": "0% for 12 months",
      "balanceTransfers": "0% for 12 months (request within 60 days)"
    },
    "regularApr": "19.49%-28.49% Variable",
    "foreignFee": "2.7%",
    "perks": [
      "$0 intro annual fee first year, then $95",
      "6% groceries and streaming",
      "Return protection (90 days)",
      "Purchase protection"
    ],
    "sourceUrl": "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/amex-blue-cash-preferred.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://icm.aexp-static.com/acquisition/card-art/NUS000000264_480x304_straight_withname.png"
    },
    "terms": {
      "id": "american-express-national-bank-blue-cash-preferred-card",
      "institution": "American Express National Bank",
      "issuerKey": "AMERICAN_EXPRESS",
      "productName": "Blue Cash Preferred® Card",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": 0.2899,
      "aprPoor": null,
      "aprGood": 0.2899,
      "aprGreat": 0.2674,
      "aprMin": 0.1949,
      "aprMax": 0.2849,
      "introApr": 0.0,
      "introMonths": 12.0,
      "btApr": 0.0,
      "btMonths": 12.0,
      "btFeePct": 0.03,
      "btFeeMin": 5.0,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 10.0,
      "graceDays": 25.0,
      "annualFee": 95.0,
      "foreignFeePct": 0.027,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards"
      ]
    },
    "tccpId": "american-express-national-bank-blue-cash-preferred-card",
    "unverified": true,
    "unverifiedFields": [
      "welcomeOffer",
      "introApr",
      "regularApr"
    ]
  },
  {
    "slug": "capital-one-venture-x",
    "name": "Capital One Venture X Rewards",
    "issuer": "Capital One",
    "network": "Visa",
    "creditNeeded": "excellent",
    "secured": false,
    "student": false,
    "annualFee": 395,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Capital One miles",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 10,
        "unit": "x",
        "note": "hotels and rental cars via Capital One Travel; 5x flights and vacation rentals"
      },
      {
        "category": "entertainment",
        "rate": 5,
        "unit": "x",
        "note": "Capital One Entertainment"
      },
      {
        "category": "everything",
        "rate": 2,
        "unit": "x"
      }
    ],
    "welcomeOffer": {
      "text": "Earn 75,000 bonus miles after spending $4,000 in the first 3 months",
      "valueUsd": 750.0,
      "spend": 4000,
      "months": 3
    },
    "introApr": null,
    "regularApr": "19.49%-28.49% Variable",
    "foreignFee": "None",
    "perks": [
      "$300 annual Capital One Travel credit",
      "10,000 bonus miles every anniversary",
      "Capital One Lounges + 1,300+ Priority Pass lounges",
      "Transfer to 15+ travel partners"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/venture-x/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-venture-x.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/venturex-cg-static-card-1000x630-2.png"
    },
    "terms": {
      "id": "capital-one-venture-x-rewards",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Venture X Rewards",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": 0.2924,
      "aprGood": 0.2924,
      "aprGreat": 0.2524,
      "aprMin": 0.1949,
      "aprMax": 0.2849,
      "introApr": null,
      "introMonths": null,
      "btApr": 0.0,
      "btMonths": 12.0,
      "btFeePct": 0.04,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 395.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Travel-related rewards"
      ]
    },
    "tccpId": "capital-one-venture-x-rewards"
  },
  {
    "slug": "capital-one-venture",
    "name": "Capital One Venture Rewards",
    "issuer": "Capital One",
    "network": "Visa",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 95,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Capital One miles",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "x",
        "note": "hotels, vacation rentals and rental cars via Capital One Travel"
      },
      {
        "category": "entertainment",
        "rate": 5,
        "unit": "x",
        "note": "Capital One Entertainment"
      },
      {
        "category": "everything",
        "rate": 2,
        "unit": "x"
      }
    ],
    "welcomeOffer": {
      "text": "Earn 75,000 bonus miles once you spend $4,000 on purchases in the first 3 months",
      "valueUsd": 750.0,
      "spend": 4000,
      "months": 3
    },
    "introApr": null,
    "regularApr": "19.49%-28.49% Variable",
    "foreignFee": "None",
    "perks": [
      "Up to $120 Global Entry/TSA PreCheck credit",
      "One-time $300 Capital One Travel stays credit",
      "$50 Lifestyle Collection experience credit",
      "Transfer miles to 15+ partners"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/venture/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-venture.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/venture_cardart_prim_323x203-1.png"
    },
    "terms": {
      "id": "capital-one-venture-rewards",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Venture Rewards",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": 0.2924,
      "aprGood": 0.2924,
      "aprGreat": 0.2524,
      "aprMin": 0.1949,
      "aprMax": 0.2849,
      "introApr": null,
      "introMonths": null,
      "btApr": 0.0,
      "btMonths": 12.0,
      "btFeePct": 0.04,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 95.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Travel-related rewards"
      ]
    },
    "tccpId": "capital-one-venture-rewards"
  },
  {
    "slug": "capital-one-savor",
    "name": "Capital One Savor Cash Rewards",
    "issuer": "Capital One",
    "network": "Mastercard",
    "creditNeeded": "excellent",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "percent",
        "note": "hotels, vacation rentals, rental cars via Capital One Travel"
      },
      {
        "category": "dining",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "groceries",
        "rate": 3,
        "unit": "percent",
        "note": "excl. superstores like Walmart and Target"
      },
      {
        "category": "entertainment",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "streaming",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a one-time $200 cash bonus once you spend $500 in the first 3 months",
      "valueUsd": 200.0,
      "spend": 500,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 12 months",
      "balanceTransfers": "0% for 12 months",
      "btFee": "balance transfer fee applies"
    },
    "regularApr": "18.49%-28.49% Variable",
    "foreignFee": "None",
    "perks": [
      "No annual fee (former $95 Savor merged into no-fee Savor)",
      "3% dining, grocery, entertainment, streaming",
      "No foreign transaction fees",
      "Rewards don't expire"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/savor/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-savor.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/new-savor-card-art.png"
    },
    "terms": {
      "id": "capital-one-savor-rewards",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Savor Rewards",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": 0.2924,
      "aprGood": 0.2924,
      "aprGreat": 0.2524,
      "aprMin": 0.1849,
      "aprMax": 0.2849,
      "introApr": 0.0,
      "introMonths": 12.0,
      "btApr": 0.0,
      "btMonths": 12.0,
      "btFeePct": 0.03,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards"
      ]
    },
    "tccpId": "capital-one-savor-rewards"
  },
  {
    "slug": "capital-one-quicksilver",
    "name": "Capital One Quicksilver Cash Rewards",
    "issuer": "Capital One",
    "network": "Mastercard",
    "creditNeeded": "excellent",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "percent",
        "note": "hotels and rental cars via Capital One Travel"
      },
      {
        "category": "everything",
        "rate": 1.5,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a one-time $200 cash bonus after spending $500 in the first 3 months",
      "valueUsd": 200.0,
      "spend": 500,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 15 months",
      "balanceTransfers": "0% for 15 months",
      "btFee": "3%"
    },
    "regularApr": "18.49%-28.49% Variable",
    "foreignFee": "None",
    "perks": [
      "Unlimited 1.5% on everything",
      "No foreign transaction fees",
      "Redeem cash back for any amount",
      "Rewards don't expire"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/quicksilver/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-quicksilver.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/qs_cardart_prim_323x203.png"
    },
    "terms": {
      "id": "capital-one-quicksilver-rewards-ranged-apr-offering",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Quicksilver Rewards (ranged APR offering)",
      "secured": false,
      "minTier": 3,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": 0.2924,
      "aprGood": 0.2924,
      "aprGreat": 0.2524,
      "aprMin": 0.1849,
      "aprMax": 0.2849,
      "introApr": 0.0,
      "introMonths": 15.0,
      "btApr": 0.0,
      "btMonths": 15.0,
      "btFeePct": 0.03,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards"
      ]
    },
    "tccpId": "capital-one-quicksilver-rewards-ranged-apr-offering",
    "unverified": true,
    "unverifiedFields": [
      "introApr",
      "regularApr",
      "welcomeOffer.spend",
      "earn.travel_portal"
    ]
  },
  {
    "slug": "capital-one-platinum",
    "name": "Capital One Platinum",
    "issuer": "Capital One",
    "network": "Mastercard",
    "creditNeeded": "fair",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "everything",
        "rate": 0,
        "unit": "percent",
        "note": "no rewards"
      }
    ],
    "welcomeOffer": null,
    "introApr": null,
    "regularApr": "28.99% Variable",
    "foreignFee": "None",
    "perks": [
      "No annual fee",
      "Automatic credit line reviews in as little as 6 months",
      "Free CreditWise credit monitoring",
      "No foreign transaction fees"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/platinum/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-platinum.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/plat_cardart_prim_323x203.png"
    },
    "terms": {
      "id": "capital-one-platinum-mastercard",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Platinum Mastercard",
      "secured": false,
      "minTier": 0,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": null,
      "aprGood": null,
      "aprGreat": null,
      "aprMin": 0.2899,
      "aprMax": 0.2899,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2974,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": []
    },
    "tccpId": "capital-one-platinum-mastercard"
  },
  {
    "slug": "capital-one-platinum-secured",
    "name": "Capital One Platinum Secured",
    "issuer": "Capital One",
    "network": "Mastercard",
    "creditNeeded": "none",
    "secured": true,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "everything",
        "rate": 0,
        "unit": "percent",
        "note": "no rewards"
      }
    ],
    "welcomeOffer": null,
    "introApr": null,
    "regularApr": "28.99% Variable",
    "foreignFee": "None",
    "perks": [
      "Refundable deposit of $49, $99 or $200 for a $200+ line",
      "Deposit more to raise line up to $1,000",
      "Can graduate to unsecured Platinum with responsible use",
      "No foreign transaction fees"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/platinum-secured/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-platinum-secured.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/plat_cardart_prim_323x203.png"
    },
    "terms": {
      "id": "capital-one-platinum-secured",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Platinum Secured",
      "secured": true,
      "minTier": 0,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": null,
      "aprGood": null,
      "aprGreat": null,
      "aprMin": 0.2899,
      "aprMax": 0.2899,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2974,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": []
    },
    "tccpId": "capital-one-platinum-secured"
  },
  {
    "slug": "capital-one-savor-student",
    "name": "Capital One Savor Student Cash Rewards",
    "issuer": "Capital One",
    "network": "Mastercard",
    "creditNeeded": "fair",
    "secured": false,
    "student": true,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "dining",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "groceries",
        "rate": 3,
        "unit": "percent",
        "note": "excl. superstores"
      },
      {
        "category": "entertainment",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "streaming",
        "rate": 3,
        "unit": "percent"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a one-time $50 cash bonus once you spend $100 in the first 3 months",
      "valueUsd": 50.0,
      "spend": 100,
      "months": 3
    },
    "introApr": null,
    "regularApr": "18.49%-28.49% Variable",
    "foreignFee": "None",
    "perks": [
      "For college students with limited credit",
      "3% dining, grocery, entertainment, streaming",
      "No annual fee",
      "No foreign transaction fees"
    ],
    "sourceUrl": "https://www.capitalone.com/credit-cards/savor-student/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/capital-one-savor-student.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/card/products/new-savor-card-art.png"
    },
    "terms": {
      "id": "capital-one-savor-rewards-for-students",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Savor Rewards for Students",
      "secured": false,
      "minTier": 0,
      "variableRate": true,
      "aprNoScore": 0.2899,
      "aprPoor": 0.2899,
      "aprGood": 0.2524,
      "aprGreat": 0.1924,
      "aprMin": 0.1849,
      "aprMax": 0.2849,
      "introApr": null,
      "introMonths": null,
      "btApr": null,
      "btMonths": null,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": 5.0,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards"
      ]
    },
    "tccpId": "capital-one-savor-rewards-for-students"
  },
  {
    "slug": "discover-it-cash-back",
    "name": "Discover it Cash Back",
    "issuer": "Discover (Capital One)",
    "network": "Discover",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "rotating",
        "rate": 5,
        "unit": "percent",
        "cap": "up to quarterly maximum ($1,500) when activated",
        "annualCap": 6000.0,
        "note": "e.g. grocery, restaurants, gas"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Cashback Match: all cash back earned in the first year matched dollar-for-dollar",
      "valueUsd": 0.0,
      "spend": 0,
      "months": 12,
      "cashbackMatch": true
    },
    "introApr": {
      "purchases": "0% for 15 months",
      "balanceTransfers": "0% for 15 months",
      "btFee": "balance transfer fee applies"
    },
    "regularApr": "17.49%-26.49% Variable",
    "foreignFee": "None",
    "perks": [
      "Unlimited first-year Cashback Match",
      "5% rotating quarterly categories",
      "No annual fee",
      "Free FICO score via CreditWise"
    ],
    "sourceUrl": "https://www.discover.com/credit-cards/cash-back/it-card.html",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/discover-it-cash-back.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/dfs-card/products/cardart-cashit-with-shadow.png"
    },
    "terms": {
      "id": "capital-one-discover-it-cash-back-credit-card",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Discover it® Cash Back Credit Card",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": 0.2699,
      "aprPoor": null,
      "aprGood": 0.2674,
      "aprGreat": 0.2474,
      "aprMin": 0.1749,
      "aprMax": 0.2649,
      "introApr": 0.0,
      "introMonths": 15.0,
      "btApr": 0.0,
      "btMonths": 15.0,
      "btFeePct": 0.03,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": null,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 0.0,
      "rewards": [
        "Cashback rewards",
        "Other rewards"
      ]
    },
    "tccpId": "capital-one-discover-it-cash-back-credit-card",
    "unverified": true,
    "unverifiedFields": [
      "earn.rotating.cap"
    ]
  },
  {
    "slug": "discover-it-student",
    "name": "Discover it Student Cash Back",
    "issuer": "Discover (Capital One)",
    "network": "Discover",
    "creditNeeded": "none",
    "secured": false,
    "student": true,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "rotating",
        "rate": 5,
        "unit": "percent",
        "cap": "up to quarterly maximum when activated",
        "annualCap": 6000.0
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Limited time: $100 statement credit after $300 in the first 3 months, plus first-year Cashback Match",
      "valueUsd": 100.0,
      "spend": 300,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 6 months"
    },
    "regularApr": "16.49%-25.49% Variable",
    "foreignFee": "None",
    "perks": [
      "No credit score required to apply",
      "First-year Cashback Match",
      "5% rotating categories",
      "No annual fee"
    ],
    "sourceUrl": "https://www.discover.com/credit-cards/student/it-card.html",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/discover-it-student.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/dfs-card/products/cardart-student-it-iridescent-shadow.png"
    },
    "terms": {
      "id": "capital-one-discover-it-student-cash-back",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Discover It® Student Cash Back",
      "secured": false,
      "minTier": 0,
      "variableRate": true,
      "aprNoScore": 0.2474,
      "aprPoor": null,
      "aprGood": 0.2374,
      "aprGreat": 0.1724,
      "aprMin": 0.1649,
      "aprMax": 0.2549,
      "introApr": 0.0,
      "introMonths": 6.0,
      "btApr": 0.1099,
      "btMonths": 6.0,
      "btFeePct": 0.03,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": null,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 0.0,
      "rewards": [
        "Cashback rewards",
        "Other rewards"
      ]
    },
    "tccpId": "capital-one-discover-it-student-cash-back"
  },
  {
    "slug": "discover-it-secured",
    "name": "Discover it Secured Credit Card",
    "issuer": "Discover (Capital One)",
    "network": "Discover",
    "creditNeeded": "none",
    "secured": true,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "rotating",
        "rate": 5,
        "unit": "percent",
        "cap": "up to quarterly maximum when activated",
        "annualCap": 6000.0
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Cashback Match: all cash back earned in the first year matched",
      "valueUsd": 0.0,
      "spend": 0,
      "months": 12,
      "cashbackMatch": true
    },
    "introApr": null,
    "regularApr": "27.24% Variable",
    "foreignFee": "None",
    "perks": [
      "Refundable deposit $49, $99 or $200 for a $200+ line",
      "Earn deposit back and upgrade to Discover it Cash Back",
      "First-year Cashback Match",
      "No credit score required to apply"
    ],
    "sourceUrl": "https://www.discover.com/credit-cards/secured/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/discover-it-secured.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://ecm.capitalone.com/WCM/dfs-card/products/cardart-cashit-with-shadow.png"
    },
    "terms": {
      "id": "capital-one-discover-it-secured-credit-card",
      "institution": "Capital One, National Association",
      "issuerKey": "CAPITAL_ONE",
      "productName": "Discover It® Secured Credit Card",
      "secured": true,
      "minTier": 0,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": null,
      "aprGood": null,
      "aprGreat": null,
      "aprMin": 0.2724,
      "aprMax": 0.2724,
      "introApr": null,
      "introMonths": null,
      "btApr": 0.1099,
      "btMonths": 6.0,
      "btFeePct": 0.03,
      "btFeeMin": null,
      "cashApr": 0.2924,
      "cashFeePct": 0.05,
      "cashFeeMin": null,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.0,
      "lateFee": 0.0,
      "rewards": [
        "Cashback rewards",
        "Other rewards"
      ]
    },
    "tccpId": "capital-one-discover-it-secured-credit-card",
    "unverified": true,
    "unverifiedFields": [
      "regularApr"
    ]
  },
  {
    "slug": "citi-double-cash",
    "name": "Citi Double Cash Card",
    "issuer": "Citi",
    "network": "Mastercard",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Citi ThankYou",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "travel_portal",
        "rate": 5,
        "unit": "percent",
        "note": "hotels, car rentals, attractions via Citi Travel"
      },
      {
        "category": "everything",
        "rate": 2,
        "unit": "percent",
        "note": "1% when you buy + 1% when you pay"
      }
    ],
    "welcomeOffer": {
      "text": "Earn $200 cash back after spending $1,500 in the first 6 months",
      "valueUsd": 200.0,
      "spend": 1500,
      "months": 6
    },
    "introApr": {
      "balanceTransfers": "0% for 18 months",
      "btFee": "3% intro (first 4 months) then 5%"
    },
    "regularApr": "18.24%-28.49% Variable",
    "foreignFee": "3%",
    "perks": [
      "Unlimited 2% on everything",
      "No annual fee",
      "Redeem as statement credit, check or direct deposit",
      "Citi Entertainment access"
    ],
    "sourceUrl": "https://www.cnbc.com/select/citi-double-cash-card-review/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/citi-double-cash.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://aemapi.citi.com/content/dam/cfs/uspb/usmkt/cards/en/static/images/citi-double-cash-credit-card/citi-double-cash-credit-card_306x192.webp"
    },
    "terms": {
      "id": "citibank-citi-double-cash-card",
      "institution": "Citibank, N.A.",
      "issuerKey": "CITI",
      "productName": "Citi Double Cash Card",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": null,
      "aprGood": 0.2749,
      "aprGreat": 0.1749,
      "aprMin": 0.1824,
      "aprMax": 0.2849,
      "introApr": null,
      "introMonths": null,
      "btApr": 0.0,
      "btMonths": 9.0,
      "btFeePct": 0.05,
      "btFeeMin": null,
      "cashApr": 0.2974,
      "cashFeePct": 0.05,
      "cashFeeMin": null,
      "graceDays": 23.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": 41.0,
      "rewards": [
        "Cashback rewards"
      ]
    },
    "tccpId": "citibank-citi-double-cash-card",
    "unverified": true,
    "unverifiedFields": [
      "all terms from secondary source"
    ]
  },
  {
    "slug": "citi-custom-cash",
    "name": "Citi Custom Cash Card",
    "issuer": "Citi",
    "network": "Mastercard",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "Citi ThankYou",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "top_category",
        "rate": 5,
        "unit": "percent",
        "cap": "$500 per billing cycle, then 1%",
        "annualCap": 6000.0,
        "note": "auto-applies to your top eligible category"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": null,
    "introApr": null,
    "regularApr": "unverified",
    "foreignFee": "3%",
    "perks": [
      "5% on top spend category each cycle",
      "No annual fee",
      "Closed to new applicants since May 28, 2026",
      "Existing cardholders keep benefits"
    ],
    "sourceUrl": "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/citi-custom-cash.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://aemapi.citi.com/content/dam/cfs/uspb/usmkt/cards/en/static/images/citi-custom-cash-credit-card/citi-custom-cash-credit-card_306x192.webp"
    },
    "terms": {
      "id": "citibank-citi-custom-cash",
      "institution": "Citibank, N.A.",
      "issuerKey": "CITI",
      "productName": "Citi Custom Cash",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": null,
      "aprGood": 0.2749,
      "aprGreat": 0.1749,
      "aprMin": 0.1749,
      "aprMax": 0.2749,
      "introApr": null,
      "introMonths": null,
      "btApr": 0.0,
      "btMonths": 9.0,
      "btFeePct": 0.05,
      "btFeeMin": null,
      "cashApr": 0.2974,
      "cashFeePct": 0.05,
      "cashFeeMin": null,
      "graceDays": 23.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": 41.0,
      "rewards": [
        "Other rewards"
      ]
    },
    "tccpId": "citibank-citi-custom-cash",
    "unverified": true,
    "unverifiedFields": [
      "regularApr",
      "foreignTransactionFee"
    ],
    "closed": "closed to new applications (May 28, 2026)"
  },
  {
    "slug": "wells-fargo-active-cash",
    "name": "Wells Fargo Active Cash Card",
    "issuer": "Wells Fargo",
    "network": "Visa",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "everything",
        "rate": 2,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "Earn a $100 cash rewards bonus when you spend $500 in purchases in the first 3 months",
      "valueUsd": 100.0,
      "spend": 500,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 12 months",
      "balanceTransfers": "0% for 12 months (within 120 days)",
      "btFee": "see terms"
    },
    "regularApr": "18.49%, 24.49% or 28.49% Variable",
    "foreignFee": "3%",
    "perks": [
      "Unlimited 2% cash rewards",
      "Cell phone protection up to $600 ($25 deductible)",
      "Visa Signature Hotel Collection",
      "Rewards don't expire"
    ],
    "sourceUrl": "https://creditcards.wellsfargo.com/active-cash-credit-card/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/wells-fargo-active-cash.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://creditcards.wellsfargo.com/W-Card-MarketPlace/v9-1-26/images/Products/ActiveCash/WF_ActiveCash_VS_Collateral_Front_RGB.png"
    },
    "terms": {
      "id": "wells-fargo-bank-wells-fargo-active-cash-card",
      "institution": "Wells Fargo Bank, National Association",
      "issuerKey": "WELLS_FARGO",
      "productName": "Wells Fargo Active Cash Card",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": 0.2849,
      "aprGood": 0.2849,
      "aprGreat": 0.2449,
      "aprMin": 0.1849,
      "aprMax": 0.2849,
      "introApr": 0.0,
      "introMonths": 13.0,
      "btApr": 0.0,
      "btMonths": 13.0,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2949,
      "cashFeePct": null,
      "cashFeeMin": null,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": null,
      "rewards": [
        "Cashback rewards",
        "Travel-related rewards",
        "Other rewards"
      ]
    },
    "tccpId": "wells-fargo-bank-wells-fargo-active-cash-card"
  },
  {
    "slug": "wells-fargo-reflect",
    "name": "Wells Fargo Reflect Card",
    "issuer": "Wells Fargo",
    "network": "Visa",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "everything",
        "rate": 0,
        "unit": "percent",
        "note": "no rewards; built for intro APR"
      }
    ],
    "welcomeOffer": null,
    "introApr": {
      "purchases": "0% for 21 months",
      "balanceTransfers": "0% for 21 months (within 120 days)",
      "btFee": "see terms"
    },
    "regularApr": "17.49%, 23.99% or 28.24% Variable",
    "foreignFee": "3%",
    "perks": [
      "21-month 0% intro APR on purchases and balance transfers",
      "Cell phone protection up to $600 ($25 deductible)",
      "Roadside Dispatch",
      "No annual fee"
    ],
    "sourceUrl": "https://creditcards.wellsfargo.com/reflect-visa-credit-card/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/wells-fargo-reflect.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://creditcards.wellsfargo.com/rv/bcs/production/reflect.B_Nc3OR8_Z2bs2bf.webp"
    },
    "terms": {
      "id": "wells-fargo-bank-wells-fargo-reflect-card",
      "institution": "Wells Fargo Bank, National Association",
      "issuerKey": "WELLS_FARGO",
      "productName": "Wells Fargo Reflect Card",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": null,
      "aprPoor": 0.2824,
      "aprGood": 0.2824,
      "aprGreat": 0.2399,
      "aprMin": 0.1749,
      "aprMax": 0.2824,
      "introApr": 0.0,
      "introMonths": 22.0,
      "btApr": 0.0,
      "btMonths": 22.0,
      "btFeePct": null,
      "btFeeMin": null,
      "cashApr": 0.2949,
      "cashFeePct": null,
      "cashFeeMin": null,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": null,
      "rewards": []
    },
    "tccpId": "wells-fargo-bank-wells-fargo-reflect-card"
  },
  {
    "slug": "bofa-customized-cash",
    "name": "Bank of America Customized Cash Rewards",
    "issuer": "Bank of America",
    "network": "Visa",
    "creditNeeded": "good",
    "secured": false,
    "student": false,
    "annualFee": 0,
    "firstYearFeeWaived": false,
    "rewardsCurrency": "cash",
    "centsPerPoint": 1.0,
    "earn": [
      {
        "category": "top_category",
        "rate": 6,
        "unit": "percent",
        "cap": "$2,500 combined 6%/2% per quarter, then 1%",
        "annualCap": 10000.0,
        "note": "choice category 6% first year then 3%: gas/EV, online shopping, dining, travel, drugstores, home improvement"
      },
      {
        "category": "groceries",
        "rate": 2,
        "unit": "percent",
        "cap": "shares $2,500 quarterly cap",
        "annualCap": 10000.0,
        "note": "grocery stores and wholesale clubs"
      },
      {
        "category": "everything",
        "rate": 1,
        "unit": "percent"
      }
    ],
    "welcomeOffer": {
      "text": "$200 cash rewards bonus after $1,000 in purchases in the first 90 days",
      "valueUsd": 200.0,
      "spend": 1000,
      "months": 3
    },
    "introApr": {
      "purchases": "0% for 15 billing cycles",
      "balanceTransfers": "0% for 15 billing cycles (within 60 days)",
      "btFee": "3% for first 60 days, then 5%"
    },
    "regularApr": "17.49%-27.49% Variable",
    "foreignFee": "3%",
    "perks": [
      "Choose your 3% category, changeable monthly",
      "6% choice category in year one",
      "Preferred Rewards members earn 25%-75% more",
      "No annual fee"
    ],
    "sourceUrl": "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/",
    "checked": "2026-09-11",
    "art": {
      "src": "/cards/art/bofa-customized-cash.webp",
      "width": 1200,
      "height": 757,
      "sourceUrl": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8ckn_cshsigcm_v_250x158.png"
    },
    "terms": {
      "id": "bank-of-america-bank-of-america-customized-cash-rewards",
      "institution": "Bank Of America, National Association",
      "issuerKey": "BANK_OF_AMERICA",
      "productName": "Bank of America Customized Cash Rewards",
      "secured": false,
      "minTier": 2,
      "variableRate": true,
      "aprNoScore": 0.2574,
      "aprPoor": 0.2799,
      "aprGood": 0.2624,
      "aprGreat": 0.2199,
      "aprMin": 0.1749,
      "aprMax": 0.2749,
      "introApr": 0.0,
      "introMonths": 15.0,
      "btApr": 0.0,
      "btMonths": 15.0,
      "btFeePct": 0.04,
      "btFeeMin": null,
      "cashApr": 0.2874,
      "cashFeePct": 0.05,
      "cashFeeMin": null,
      "graceDays": 25.0,
      "annualFee": 0.0,
      "foreignFeePct": 0.03,
      "lateFee": 29.0,
      "rewards": [
        "Cashback rewards",
        "Other rewards"
      ]
    },
    "tccpId": "bank-of-america-bank-of-america-customized-cash-rewards",
    "unverified": true,
    "unverifiedFields": [
      "foreignTransactionFee"
    ]
  }
];
