// A curated overlay for onboarding's 3-card picker: a fixed slug list into
// `CURATED` rather than a field on `CuratedCard` (which is generated by
// research/data/cards/build_cards.py and must never be hand-edited). Reused
// wherever a "first card" pick needs a short, genuinely beginner-appropriate
// list — onboarding today, possibly the Money desk's Card Shop later.

import type { CuratedCard } from "../sim/money/types.ts";
import { CURATED } from "./cards-curated.ts";

/**
 * A no-annual-fee secured card and two no-annual-fee student/secured cards:
 * easy approval, nothing to owe just for carrying them.
 */
export const BEGINNER_CARD_SLUGS = ["capital-one-platinum-secured", "discover-it-student", "discover-it-secured"] as const;

export const BEGINNER_CARDS: CuratedCard[] = CURATED.filter((c) => (BEGINNER_CARD_SLUGS as readonly string[]).includes(c.slug));
