// Builds src/data/market.ts from FRED's keyless CSV export: a year of the
// S&P 500, Nasdaq, Dow, the Fed funds rate, the 10-year Treasury, and the
// 30-year mortgage rate. The game ships this snapshot so it never depends on
// a live API; Alpha Vantage quotes (vite.config.ts) layer on top when a key is set.
// Run from game/: `npm run market:snapshot`.

import { writeFileSync } from "node:fs";

const SERIES = [
  { id: "SP500", name: "S&P 500", unit: "index" },
  { id: "NASDAQCOM", name: "Nasdaq Composite", unit: "index" },
  { id: "DJIA", name: "Dow Jones Industrial Average", unit: "index" },
  { id: "DFF", name: "Fed funds rate", unit: "percent" },
  { id: "DGS10", name: "10-year Treasury yield", unit: "percent" },
  { id: "MORTGAGE30US", name: "30-year fixed mortgage", unit: "percent" },
] as const;

const SINCE = "2025-09-01";

async function fetchSeries(id: string): Promise<[string, number][]> {
  const res = await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${id}&cosd=${SINCE}`);
  if (!res.ok) throw new Error(`FRED ${id}: HTTP ${res.status}`);
  const rows = (await res.text()).trim().split("\n").slice(1);
  return rows
    .map((r) => r.split(","))
    .filter(([, v]) => v !== undefined && v !== "" && v !== ".")
    .map(([d, v]) => [d, Number(v)] as [string, number])
    .filter(([, v]) => Number.isFinite(v));
}

const out: Record<string, { name: string; unit: string; points: [string, number][] }> = {};
for (const s of SERIES) {
  out[s.id] = { name: s.name, unit: s.unit, points: await fetchSeries(s.id) };
  console.log(`${s.id}: ${out[s.id].points.length} points, last ${out[s.id].points.at(-1)?.join(" = ")}`);
}
const asOf = Object.values(out)
  .map((s) => s.points.at(-1)?.[0] ?? "")
  .sort()
  .at(-1);

const body = `// Generated by scripts/build-market-snapshot.ts from FRED (Federal Reserve Bank of St. Louis).
// Do not edit by hand; rerun \`npm run market:snapshot\` instead.
// Index levels are for display and education only (S&P and Dow Jones data are licensed to FRED for viewing).

export interface MarketSeries {
  name: string;
  unit: "index" | "percent";
  points: [string, number][];
}

export const MARKET = {
  source: "FRED",
  asOf: ${JSON.stringify(asOf)},
  series: {
${Object.entries(out)
  .map(([id, s]) => `    ${id}: { name: ${JSON.stringify(s.name)}, unit: ${JSON.stringify(s.unit)}, points: ${JSON.stringify(s.points)} } as MarketSeries,`)
  .join("\n")}
  },
};

export type SeriesId = keyof typeof MARKET.series;
`;

writeFileSync(new URL("../src/data/market.ts", import.meta.url), body);
console.log(`wrote src/data/market.ts (as of ${asOf})`);
